{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mi-aplicacion.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "mi-aplicacion.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      {{- include "mi-aplicacion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        {{- include "mi-aplicacion.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mi-aplicacion.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "mi-aplicacion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "mi-aplicacion.selectorLabels" . | nindent 4 }}
{{- end }}