spring.application.name=Ejercicio2

# Esto le dice a Spring que use el driver de Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Estas líneas son opcionales pero ayudan a que Spring no muera 
# si la DB tarda unos segundos extra en arrancar
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=update